# Generated by Django 2.2.5 on 2019-09-13 16:06

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Title')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('pdf_output', models.FileField(blank=True, null=True, upload_to=core.utils.reports_path, verbose_name='PDF')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
            },
        ),
    ]
